if(EXISTS "/home/runner/work/Battery-Emulator/Battery-Emulator/test/_codeql_build_dir/tests[1]_tests.cmake")
  include("/home/runner/work/Battery-Emulator/Battery-Emulator/test/_codeql_build_dir/tests[1]_tests.cmake")
else()
  add_test(tests_NOT_BUILT tests_NOT_BUILT)
endif()
